version: '3'

services:
 proxy:
     image: rash07/nginx-proxy:2.0
     ports:
         - "80:80"
         - "443:443"
     volumes:
         - ./../certs:/etc/nginx/certs
         - /var/run/docker.sock:/tmp/docker.sock:ro
     restart: always
     privileged: true
networks:
 default:
     external:
         name: proxynet
